"""m4_m5_agents_findings_and_control

Revision ID: 8abba184ef10
Revises: 6cf4d8db879f
Create Date: 2026-07-14 14:46:55.129400

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '8abba184ef10'
down_revision: Union[str, Sequence[str], None] = '6cf4d8db879f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('agent_runs',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('review_job_id', sa.UUID(), nullable=False),
    sa.Column('agent_name', sa.String(length=100), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('output', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('tokens_used', sa.Integer(), nullable=False),
    sa.Column('started_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['review_job_id'], ['review_jobs.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_agent_runs_review_job_id'), 'agent_runs', ['review_job_id'], unique=False)
    op.create_table('findings',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('review_job_id', sa.UUID(), nullable=False),
    sa.Column('source_document_id', sa.UUID(), nullable=True),
    sa.Column('finding_type', sa.String(length=50), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['review_job_id'], ['review_jobs.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['source_document_id'], ['documents.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_findings_review_job_id'), 'findings', ['review_job_id'], unique=False)
    op.create_index(op.f('ix_findings_source_document_id'), 'findings', ['source_document_id'], unique=False)
    op.add_column('review_jobs', sa.Column('enabled_checks', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    op.add_column('review_jobs', sa.Column('custom_instructions', sa.Text(), nullable=True))
    op.add_column('review_jobs', sa.Column('current_node', sa.String(length=100), nullable=True))
    op.add_column('review_jobs', sa.Column('paused_state', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('review_jobs', 'paused_state')
    op.drop_column('review_jobs', 'current_node')
    op.drop_column('review_jobs', 'custom_instructions')
    op.drop_column('review_jobs', 'enabled_checks')
    op.drop_index(op.f('ix_findings_source_document_id'), table_name='findings')
    op.drop_index(op.f('ix_findings_review_job_id'), table_name='findings')
    op.drop_table('findings')
    op.drop_index(op.f('ix_agent_runs_review_job_id'), table_name='agent_runs')
    op.drop_table('agent_runs')
    # ### end Alembic commands ###
